version: '3.5'

services:

    adr-postgis:
        container_name: adr-postgis
        build:
            context: ./docker-images/postgis
            args:
                postgres_version: 13
                postgis_version: 3
        environment:
            - POSTGRES_USER=adr
            - POSTGRES_PASSWORD=adr
        #ports:
        #  - "5432:5432"
        volumes:
            - postgis-data:/var/lib/postgresql/data
            - ./scripts:/tmp/scripts
            - ./housenumber-id-ign:/tmp/housenumber-id-ign
            - ./ban:/tmp/ban
        restart: always
        #command: ["postgres", "-c", "log_statement=all"]
        shm_size: 2g

    adr-adminer:
        container_name: adr-adminer
        image: adminer
        ports:
          - "8181:8080"
        environment: 
          - ADMINER_DEFAULT_SERVER=adr-postgis
          - ADMINER_DESIGN=hydra

    adr-api:
        container_name: adr-api
        build:
            context: ./docker-images/api
        ports:
          - "80:8080"

volumes:
    postgis-data:
        name: postgis-data